### PR TITLE
Support for prefixed URLs

### PR DESCRIPTION
**Pull request by bziemek**
This patch makes it possible to install scullog at URLs such as `example.com/filemanager` (e.g. for use in shared environments and/or behind reverse proxies) by launching the app with the `-P | --prefix` flag. This patch uses [koa-router](https://github.com/alexmingoia/koa-router)'s built-in prefix support with only minor adjustments made to path handling throughout the rest of the app.

I intended to also enable Angular's [HTML5 location API support](https://docs.angularjs.org/guide/$location#-location-service-configuration) (instead of hash strings) within this patch, however something about this app and/or patch is incompatible with that mode. I left a comment at [client/js/index.js:7](https://github.com/bziemek/scullog/blob/9023d388167b15999c0ce7277dc99e23752ec67c/client/js/index.js#L5-L8) for future reference.

### CODE REVIEW

**Comment by sanketbajoria** [comment]
Awesome work, Brian :+1: 
Few issues, i have seen in the patch. When running at default path "/", it's not working. 
If passing as parameter -P "/scullog", then, the server didn't get start up on windows. 
Default path, to be redirected toward "/" + conf.prefix. 

For supporting HTML5 location API support, I need to do some changes. :)
I will fix above issue, then will merge it.

Thanks,

**Comment by bziemek** [comment]
Oops, looks like I kept my changes a little too simple!

Regarding the default path, the router is expecting requests to look like `//base`, which it won't ever get. Since koa's mount() won't take an empty string as the first argument, I've gone ahead and removed the leading `/` from each route. This seems to fix the 404s as well as the Windows crash.

**Comment by bziemek** [comment]
One thing to note: under Windows, the value of -P seems to be interpreted as a path on the filesystem, resulting in things like `"prefix":"C:/Program Files/Git/files/"` in main.json. I'll revisit this in a little while. :)

**Comment by sanketbajoria** [comment]
Yep you are right, this is issue with Git Bash. To escape the path, we can use double forward slash in windows. I think, i will update the README for the same.

**Comment by bziemek** [comment]
http://www.mingw.org/wiki/Posix_path_conversion explains this behavior, and indicates that the double forward slash is a special exception meant for Windows-style flags (i.e. `dir //w //p`).

That said, cases such as `//prefix/` (with the trailing slash as required by the changes in my latest commit) and `//pre/fix` (even without a trailing slash) will be treated as UNC paths instead. The argument will be passed with the extraneous leading slash and cause issues with the router and with socket.io.

As per that document, `//prefix\` becomes `/prefix/`, though I wouldn't wish that syntax on anyone.

On the bright side, `MSYS_NO_PATHCONV=1` disables path conversion and covers Git's default MSYS-based shell, and hence should cover 99% of installations. If anyone chooses to run the MinGW shell bundled with Git - or chooses to run Node under Cygwin - then they probably already know they signed up for some nasty caveats.

This final commit "should" complete the PR. 😉

**Comment by sanketbajoria** [comment]
Already fixed

**Pull request closed without merging**
